routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login' , 'Admin\AdminController@login')->name('login');
Route::post('login/auth' , 'Admin\AdminController@loginAuth')->name('login.auth');
Route::get('logout' , 'Admin\AdminController@logout')->name('logout');

Route::prefix('admin')->middleware('auth')->group(function() {

	Route::get('welcome' , 'Admin\AdminController@index')->name('welcome');
	Route::resource('categories' , 'Admin\CategoryController');
	Route::resource('subcategories' , 'Admin\SubCategoryController');
	Route::resource('subsubcategories' , 'Admin\SubSubCategoryController');
	Route::resource('contents' , 'Admin\ContentController');
	Route::resource('settings' , 'Admin\SettingController');
	Route::get('subcat' , 'Admin\ContentController@subcat')->name('subcat');
	Route::get('subsubcat' , 'Admin\ContentController@subsubcat')->name('subsubcat');

});

// route index
Route::get('locale/{locale}' , 'Website\LocaleController@locale')->name('locale');
Route::get('/' , 'Website\IndexController@index');

app/Http/Controllers/Admin/SubCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\CategoryRequest;
use App\Repository\CategoriesRepositoryInterface;

class SubCategoryController extends Controller
{

	protected $categoryrepository;

	public function __construct(CategoriesRepositoryInterface $categoryrepository)
	{

		$this->categoryrepository = $categoryrepository;

	} // end of construct

    public function index()
    {

        // messages success
        if (session('success')) {
            alert()->success('ناجح',session('success'));
        }         

    	$subcategories = $this->categoryrepository->allSubCategories();

    	return view('Admin.subcategories.index' , compact('subcategories'));

    } // end of index

    public function create()
    {

    	$categories = $this->categoryrepository->allMainCategories();
    	return view('Admin.subcategories.create' , compact('categories'));

    } // end of create

    public function store(CategoryRequest $request)
    {
    	$request->validate(['parent_id' => 'required']);

    	$this->categoryrepository->create(array_merge($request->except('_token' , '_method') , ['type' => 2]));
    	return redirect()->route('subcategories.index')->with('success' , 'تم اضافه القسم بنجاح');

    } // end of store

    public function edit($category)
    {

    	$categories = $this->categoryrepository->allMainCategories();

    	$category = $this->categoryrepository->find($category);
    	return view('Admin.subcategories.edit' , compact('category' , 'categories'));

    } // end of edit

    public function update(CategoryRequest $request , $category)
    {
    	
    	$this->categoryrepository->update($category , array_merge($request->except('_token' , '_method') , ['type' => 2]));

    	return redirect()->route('subcategories.index')->with('success' , 'تم تعديل القسم بنجاح');
    	

    } // end of edit 

    public function destroy($category)
    {

    	$this->categoryrepository->destroy($category);

    	return redirect()->route('subcategories.index')->with('success' , 'تم حذف القسم بنجاح');
    	

    } // end of edit    

} // end of class

resources/views/Admin/subcategories/create.blade.php
@extends('Admin.layout.app')
@section('title')
اضاقه قسم فرعي
@endsection
@section('content')
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">الأقسام</h2>
                            <div class="breadcrumb-wrapper col-12">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('welcome')}}">الرئيسية</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{route('categories.index')}}">الأقسام</a>
                                    </li>
                                    <li class="breadcrumb-item active">{{isset($category)?'تعديل قسم':'أضف قسم'}}
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">


                <!-- Input Validation start -->
                <section class="input-validation">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
@include('Admin.alert')
                                <div class="card-content">
                                    <div class="card-body">
                                        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{{ route('subcategories.store') }}" novalidate>
                                            @csrf
                                       

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>الاسم بالعربية</label>
                                                        <div class="controls">
                                                            <input type="text" name="name_ar" class="form-control" data-validation-required-message="هذا الحقل الزامي" placeholder="الاسم بالعربية" value="{{isset($category)?$category->name_ar:''}}">
                                                       <div class="invalid-tooltip">
                                                           @if ($errors->has('name_ar'))
                                                               <span class="help-block">
                                                                 <strong style="color: red;">{{ $errors->first('name_ar') }}</strong>
                                                                </span>
                                                           @endif
                                                       </div>
                                                        </div>
                                                    </div>



                                                </div>

                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>الاسم بالإنجليزية</label>
                                                        <div class="controls">
                                                            <input type="text" name="name_en" class="form-control" required data-validation-required-message="هذا الحقل الزامي" placeholder="الاسم بالإنجليزية" value="{{isset($category)?$category->name_en:''}}">
                                                            <div class="invalid-tooltip">
                                                                @if ($errors->has('name_en'))
                                                                    <span class="help-block">
                                                                        <strong style="color: red;">{{ $errors->first('name_en') }}</strong>
                                                                    </span>
                                                                @endif
                                                            </div>
                                                        </div>
                                                    </div>


                                                </div>
                                            </div>

                                            <div class="col-12">
                                                <div class="card">
                                                    <div class="">
                                                        <h4 class="card-title" style="margin-bottom: 20px">اختر نوع القسم</h4>
                                                    </div>

                                                            <ul class="list-unstyled mb-0">
                                                             @foreach($categories as $main_category)
                                                                <li class="mr-2">
                                                                    <fieldset>
                                                                        <label>
                                                                            <input type="radio" name="parent_id" value="{{$main_category->id}}" {{ old('parent_id') == $main_category->id?'checked':''}} required>
                                                                            {{$main_category->name_ar}}
                                                                        </label>
                                                                    </fieldset>
                                                                </li>
                                                                @endforeach

                                                            </ul>

                                                </div>
                                            </div>

                                            <button type="submit" class="btn btn-primary">حفظ</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Input Validation end -->

            </div>
        </div>
    </div>
    <!-- END: Content-->

@endsection

resources/views/Admin/subcategories/edit.blade.php
@extends('Admin.layout.app')
@section('title')
اضاقه قسم فرعي
@endsection
@section('content')
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">الاقسام الفرعيه</h2>
                            <div class="breadcrumb-wrapper col-12">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('welcome')}}">الرئيسية</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{route('categories.index')}}">تعديل</a>
                                    </li>
                                    
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">


                <!-- Input Validation start -->
                <section class="input-validation">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
@include('Admin.alert')
                                <div class="card-content">
                                    <div class="card-body">
                                        <form class="form-horizontal" method="post" action="{{ route('subcategories.update' , $category->id) }}" novalidate>
                                            @csrf
                                            @method('PUT')
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>الاسم بالعربية</label>
                                                        <div class="controls">
                                                            <input type="text" name="name_ar" class="form-control" data-validation-required-message="هذا الحقل الزامي" placeholder="الاسم بالعربية" value="{{isset($category)?$category->name_ar:''}}">
                                                       <div class="invalid-tooltip">
                                                           @if ($errors->has('name_ar'))
                                                               <span class="help-block">
                               <strong style="color: red;">{{ $errors->first('name_ar') }}</strong>
                            </span>
                                                           @endif
                                                       </div>
                                                        </div>
                                                    </div>



                                                </div>

                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>الاسم بالإنجليزية</label>
                                                        <div class="controls">
                                                            <input type="text" name="name_en" class="form-control" required data-validation-required-message="هذا الحقل الزامي" placeholder="الاسم بالإنجليزية" value="{{isset($category)?$category->name_en:''}}">
                                                            <div class="invalid-tooltip">
                                                                @if ($errors->has('name_en'))
                                                                    <span class="help-block">
                               <strong style="color: red;">{{ $errors->first('name_en') }}</strong>
                            </span>
                                                                @endif
                                                            </div>
                                                        </div>
                                                    </div>


                                                </div>
                                            </div>
                                            
                                            <div class="col-12">
                                                <div class="card">
                                                    <div class="">
                                                        <h4 class="card-title"  style="margin-bottom: 20px">اختر نوع القسم</h4>
                                                    </div>

                                                            <ul class="list-unstyled mb-0">
                                                             @foreach($categories as $main_category)
                                                                <li class="mr-2">
                                                                    <fieldset>
                                                                        <label>
                                                                            <input type="radio" name="parent_id" value="{{$main_category->id}}" {{isset($category) &&$category->parent_id ==$main_category->id?'checked':''}} {{isset($category)?'':'required'}}>
                                                                            {{$main_category->name_ar}}
                                                                        </label>
                                                                    </fieldset>
                                                                </li>
                                                                @endforeach

                                                            </ul>

                                                </div>
                                            </div>

                                   
                                            <button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> تعديل </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Input Validation end -->

            </div>
        </div>
    </div>
    <!-- END: Content-->

@endsection

resources/views/Admin/subcategories/index.blade.php
@extends('Admin.layout.app')
@section('title')
الاقسام
@endsection
@section('content')
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">الاقسام الفرعيه</h2>
                            <div class="breadcrumb-wrapper col-12">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('welcome')}}">الرئيسية</a>
                                    </li>
                                    <li class="breadcrumb-item active">الاقسام الفرعيه
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrum-right">
                        <div class="dropdown">
                            <a href="{{route('subcategories.create')}}" class="btn btn-primary">
                                <i class="fa fa-plus"></i>اضافه</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">

                <!-- Zero configuration table -->
                <section id="basic-datatable">
                    <div class="row">
                        <div class="col-12">
                            @include('Admin.alert')
                            <div class="card">
                                <div class="card-content">
                                    <div class="card-body card-dashboard">
                                        <div class="table-responsive">
                                            <table class="table zero-configuration">
                                                <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>الإسم بالعربيه</th>
                                                    <th>نوع القسم</th>
                                                    <th>تاريخ الانشاء</th>
                                                    <th>الخيارات</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                @php $i=1;@endphp
                                                @foreach($subcategories as $category)
                                                <tr>
                                                    <td>{{$i++}}</td>
                                                    <td>{{ \Illuminate\Support\Str::limit($category->name_ar , 10) }}</td>
                                                    <td>{{ $category->type }}</td>
                                                    <td>{{$category->created_at->format("d/m/Y")}}</td>
                                                    
                                                    <td>
                                                        <a href="{{route('subcategories.edit',$category->id)}}" class="action-edit"><i class="feather icon-edit"></i></a>
                                                        <form action="{{route('subcategories.destroy',$category->id)}}" method="post" style="display: inline-block">
                                                            @csrf
                                                            @method('DELETE')
                                                            <span class="action-edit"><i class="feather icon-trash"></i></span>
                                                        </form>
                                                    </td>

                                            
                                                </tr>
                                                @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!--/ Zero configuration table -->



            </div>
        </div>
    </div>
    <!-- END: Content-->
@endsection

@section('dataTable')

<!-- BEGIN: Page JS-->
<script src="{{ url('admin/app-assets/js/scripts/datatables/datatable.js') }}"></script>
<!-- END: Page JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/vfs_fonts.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/buttons.bootstrap.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<!-- END: Page Vendor JS-->


<script>
    $('.table').DataTable({
        "language": {
//            for arabic language
            "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"
        }
    });
</script>

@endsection