routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login' , 'Admin\AdminController@login')->name('login');
Route::post('login/auth' , 'Admin\AdminController@loginAuth')->name('login.auth');
Route::get('logout' , 'Admin\AdminController@logout')->name('logout');

Route::prefix('admin')->middleware('auth')->group(function() {

	Route::get('welcome' , 'Admin\AdminController@index')->name('welcome');
	Route::resource('categories' , 'Admin\CategoryController');
	Route::resource('subcategories' , 'Admin\SubCategoryController');
	Route::resource('subsubcategories' , 'Admin\SubSubCategoryController');
	Route::resource('contents' , 'Admin\ContentController');
	Route::resource('settings' , 'Admin\SettingController');
	Route::get('subcat' , 'Admin\ContentController@subcat')->name('subcat');
	Route::get('subsubcat' , 'Admin\ContentController@subsubcat')->name('subsubcat');

});

// route index
Route::get('locale/{locale}' , 'Website\LocaleController@locale')->name('locale');
Route::get('/' , 'Website\IndexController@index');

resources/views/Admin/articales/create.blade.php
@extends('Admin.layout.app')
@section('title')
اضاقه قسم فرعي
@endsection
@section('content')

    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">المحتوي</h2>
                            <div class="breadcrumb-wrapper col-12">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('welcome')}}">الرئيسية</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{route('contents.index')}}">المحتوي</a>
                                    </li>
                                    <li class="breadcrumb-item active">
                                        اضف المحتوي 
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">


                <!-- Input Validation start -->
                <section class="input-validation">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
@include('Admin.alert')
                                <div class="card-content">
                                    <div class="card-body">
                                        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{{ route('contents.store') }}" novalidate>
                                            @csrf
                                            <div class="col-12">
                                                <div class="card">

                        <div class="form-group">
                            <label>اختر القسم</label>
                            <div class="controls">
                                <select class="form-control" name="category_id" id="category">
                                    <option></option>
                                    @foreach($categories as $category)
                                    <option value="{{ $category->id }}" data-id="{{ $category->id }}" {{ $category->name_ar == old('category_id') ? old('category_id') : '' }}>{{ $category->name_ar }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>


                                                                

                                                </div>
<div class="card addsuborsubsub">
</div>                                                
                                            </div>

                                            <div class="row">

                                                <div class="col-md-12">

                                                    <div class="form-group">
                                                        <label>المحتوي بالعربي</label>
                                                        <div class="controls">
                                                            <textarea class="form-control summernote" name="content_ar">
                                                                {{ old('content_ar') }}
                                                            </textarea>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>

                                            <div class="row">

                                                <div class="col-md-12">
                                                    
                                                    <div class="form-group">
                                                        <label>المحتوي بالإنجليزية</label>
                                                        <div class="controls">
                                                            <textarea class="form-control summernote" name="content_en">
                                                                {{ old('content_en') }}
                                                            </textarea>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>

                                        {{--    <div class="row">

                                                <div class="col-md-12">
                                                    
                                                    <div class="form-group">
                                                        <label>المحتوي  الهامش بالاعربي</label>
                                                        <div class="controls">
                                                            <textarea class="form-control summernote" name="content_heddin_ar">
                                                                {{ old('content_heddin_ar') }}
                                                            </textarea>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>

                                            <div class="row">

                                                <div class="col-md-12">
                                                    
                                                    <div class="form-group">
                                                        <label>المحتوي  الهامش بالانجليزي</label>
                                                        <div class="controls">
                                                            <textarea class="form-control summernote" name="content_heddin_en">
                                                                {{ old('content_heddin_en') }}
                                                            </textarea>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>   --}}                                                                                      

                                            <button type="submit" class="btn btn-primary">حفظ</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Input Validation end -->

            </div>
        </div>
    </div>
    <!-- END: Content-->

@endsection
@section('scripts')
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

<script>
    


    $("#category").change(function ()
    {
      var category = $("#category option:selected").click();
      var id = category.data('id');
       //alert(id);

                $.ajax({

                    type: 'GET',

                    dataType: 'html',

                    url: '{{route('subcat')}}',

                    data: {

                      category_id: id

                    }, // end of data

                    success: function(data){
                     if (data == null) {
                      
                     } else {
                        $(".addsuborsubsub").html(data);
                     }
                    }

                }); // end of ajax

    });


    $('.summernote').summernote({
            height: 400,
    });
        

</script>

@endsection

resources/views/Admin/articales/edit.blade.php
@extends('Admin.layout.app')
@section('title')
اضاقه قسم فرعي
@endsection
@section('content')
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">المحتوي</h2>
                            <div class="breadcrumb-wrapper col-12">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('welcome')}}">الرئيسية</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{route('contents.index')}}">المحتوي</a>
                                    </li>
                                    <li class="breadcrumb-item active">
                                        اضف المحتوي 
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">


                <!-- Input Validation start -->
                <section class="input-validation">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
@include('Admin.alert')
                                <div class="card-content">
                                    <div class="card-body">
                                        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{{ route('contents.update' , $content->id) }}" novalidate>
                                            @csrf
                                            @method('PUT')
                                            <div class="col-12">
                                                <div class="card">

                        <div class="form-group">
                            <label>اختر القسم</label>
                            <div class="controls">
                                <select class="form-control" name="category_id" id="category">
                                    <option>اختر القسم</option>
                                    @foreach($categories as $category)
                                    <option value="{{ $category->id }}" data-id="{{ $category->id }}" {{ $content->category->name_ar == $category->name_ar ? 'selected' : '' }}>{{ $category->name_ar }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>


                                                                

                                                </div>
<div class="card addsuborsubsub">
</div>                                                
                                            </div>

                                            <div class="row">

                                                <div class="col-md-12">

                                                    <div class="form-group">
                                                        <label>المحتوي بالعربي</label>
                                                        <div class="controls">
                                                            <textarea class="form-control summernote" name="content_ar">
                                                                {{ $content->content_ar }}
                                                            </textarea>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>

                                            <div class="row">

                                                <div class="col-md-12">
                                                    
                                                    <div class="form-group">
                                                        <label>المحتوي بالإنجليزية</label>
                                                        <div class="controls">
                                                            <textarea class="form-control summernote" name="content_en">
                                                                {{ $content->content_en }}
                                                            </textarea>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>

                                         {{--   <div class="row">

                                                <div class="col-md-12">
                                                    
                                                    <div class="form-group">
                                                        <label>المحتوي  الهامش بالاعربي</label>
                                                        <div class="controls">
                                                            <textarea class="form-control summernote" name="content_heddin_ar">
                                                                {{ $content->content_heddin_ar }}
                                                            </textarea>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>

                                            <div class="row">

                                                <div class="col-md-12">
                                                    
                                                    <div class="form-group">
                                                        <label>المحتوي  الهامش بالانجليزي</label>
                                                        <div class="controls">
                                                            <textarea class="form-control summernote" name="content_heddin_en">
                                                                {{ $content->content_heddin_en }}
                                                            </textarea>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>  --}}                                          

                                            <button type="submit" class="btn btn-primary">حفظ</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Input Validation end -->

            </div>
        </div>
    </div>
    <!-- END: Content-->

@endsection

@section('scripts')

<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script>
    


    $("#category").change(function ()
    {
      var category = $("#category option:selected").click();
      var id = category.data('id');
       //alert(id);

                $.ajax({

                    type: 'GET',

                    dataType: 'html',

                    url: '{{route('subcat')}}',

                    data: {

                      category_id: id

                    }, // end of data

                    success: function(data){
                     if (data == null) {
                      
                     } else {
                        $(".addsuborsubsub").html(data);
                     }
                    }

                }); // end of ajax

    });


    $('.summernote').summernote({
            height: 400,
    });
        

</script>

@endsection

resources/views/Admin/articales/index.blade.php
@extends('Admin.layout.app')
@section('title')
الاقسام
@endsection
@section('content')
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">المحتوي</h2>
                            <div class="breadcrumb-wrapper col-12">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('welcome')}}">الرئيسية</a>
                                    </li>
                                    <li class="breadcrumb-item active">المحتوي 
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrum-right">
                        <div class="dropdown">
                            <a href="{{route('contents.create')}}" class="btn btn-primary">
                                <i class="fa fa-plus"></i>اضافه</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">

                <!-- Zero configuration table -->
                <section id="basic-datatable">
                    <div class="row">
                        <div class="col-12">
                            @include('Admin.alert')
                            <div class="card">
                                <div class="card-content">
                                    <div class="card-body card-dashboard">
                                        <div class="table-responsive">
                                            <table class="table zero-configuration">
                                                <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>المحتوي</th>
                                                    <th>القسم </th>
                                                    <th>القسم الفرعي</th>
                                                    <th>قسم فرعي اخر</th>
                                                    <th>التاريخ</th>
                                                    <th>الخيارات</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                @php $i=1;@endphp
                                                @foreach($contents as $content)
                                                <tr>
                                                    <td>{{$i++}}</td>
                                                    <td>{{ \Illuminate\Support\Str::limit(strip_tags($content->content_ar) , 20) }}</td>
                                                    <td>{{ $content->category->name_ar }}</td>
                                                    <td>{{ $content->subcategory ? $content->subcategory->name_ar : '' }}</td>
                                                    <td>{{ $content->subsubcategory ? $content->subsubcategory->name_ar : '' }}</td>
                                                    <td>{{$content->created_at->format("d/m/Y")}}</td>

                                                    <td>
                                                        <a href="{{route('contents.edit',$content->id)}}" class="action-edit"><i class="feather icon-edit"></i></a>
                                                        <form action="{{route('contents.destroy',$content->id)}}" method="post" style="display: inline-block">
                                                            @csrf
                                                            @method('DELETE')
                                                            <span class="action-edit"><i class="feather icon-trash"></i></span>
                                                        </form>
                                                    </td>
                                                </tr>
                                                @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!--/ Zero configuration table -->



            </div>
        </div>
    </div>
    <!-- END: Content-->
@endsection

@section('dataTable')

<!-- BEGIN: Page JS-->
<script src="{{ url('admin/app-assets/js/scripts/datatables/datatable.js') }}"></script>
<!-- END: Page JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/vfs_fonts.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/buttons.bootstrap.min.js') }}"></script>
<script src="{{ url('admin/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<!-- END: Page Vendor JS-->


<script>
    $('.table').DataTable({
        "language": {
//            for arabic language
            "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"
        }
    });
</script>

@endsection

resources/views/Admin/articales/subcategory.blade.php
                        @if($subcategories->count())
                        <div class="form-group">
                            <label>القسم الفرعي</label>
                            <div class="controls">
                                <select class="form-control" name="subcategory_id" id="subcategory">
                                    <option></option>
                                    @foreach($subcategories as $category)
                                    <option value="{{ $category->id }}" data-subid="{{ $category->id }}">{{ $category->name_ar }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        @endif

<script type="text/javascript">
    
    $("#subcategory").change(function ()
    {
      var category = $("#subcategory option:selected").click();
      var id = category.data('subid');
       //alert(id);

                $.ajax({

                    type: 'GET',

                    dataType: 'html',

                    url: '{{route('subsubcat')}}',

                    data: {

                      subcategory_id: id

                    }, // end of data

                    success: function(data){
                     
                      $(".addsuborsubsub").append(data);
                    }

                }); // end of ajax

    });
    
</script>            

resources/views/Admin/articales/subsubcategory.blade.php
                        @if($subsubcategories->count())
                        <div class="form-group">
                            <label>الاقسام الاخري</label>
                            <div class="controls">
                                <select class="form-control" name="subsubcategory_id" id="subsubcategory">
                                    <option></option>
                                    @foreach($subsubcategories as $category)
                                    <option value="{{ $category->id }}" data-subsubid="{{ $category->id }}">{{ $category->name_ar }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        @endif

            