routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login' , 'Admin\AdminController@login')->name('login');
Route::post('login/auth' , 'Admin\AdminController@loginAuth')->name('login.auth');
Route::get('logout' , 'Admin\AdminController@logout')->name('logout');

Route::prefix('admin')->middleware('auth')->group(function() {

	Route::get('welcome' , 'Admin\AdminController@index')->name('welcome');
	Route::resource('categories' , 'Admin\CategoryController');
	Route::resource('subcategories' , 'Admin\SubCategoryController');
	Route::resource('subsubcategories' , 'Admin\SubSubCategoryController');
	Route::resource('contents' , 'Admin\ContentController');
	Route::resource('settings' , 'Admin\SettingController');
	Route::get('subcat' , 'Admin\ContentController@subcat')->name('subcat');
	Route::get('subsubcat' , 'Admin\ContentController@subsubcat')->name('subsubcat');

});

// route index
Route::get('locale/{locale}' , 'Website\LocaleController@locale')->name('locale');
Route::get('/' , 'Website\IndexController@index');

resources/views/Admin/layout/app.blade.php
<!DOCTYPE html>
<html class="loading" lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>الدليل  | @yield('title') </title>

    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@700&display=swap" rel="stylesheet">

    <meta name="apple-mobile-web-app-status-bar-style" content="#124e23">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="apple-touch-icon" sizes="57x57" href="{{ url('Website/images/favicon/apple-icon-57x57.png') }}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ url('Website/images/favicon/apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ url('Website/images/favicon/apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ url('Website/images/favicon/apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ url('Website/images/favicon/apple-icon-114x114.png') }}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ url('Website/images/favicon/apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ url('Website/images/favicon/apple-icon-144x144.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ url('Website/') }}images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url('Website/images/favicon/apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" sizes="192x192" href="{{ url('Website/images/favicon/android-icon-192x192.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url('Website/images/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url('Website/images/favicon/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url('Website/images/favicon/favicon-16x16.png') }}">

    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/vendors/css/vendors.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/vendors/css/pickers/pickadate/pickadate.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/vendors/css/tables/datatable/datatables.min.css') }}">


    <!-- BEGIN: style CSS arabic  -->
<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">‏  -->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/vendors/css/vendors-rtl.min.css') }}">


    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/bootstrap.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/bootstrap-extended.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/colors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/components.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/themes/dark-layout.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/themes/semi-dark-layout.css') }}">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/core/menu/menu-types/vertical-menu.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/core/colors/palette-gradient.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/pages/dashboard-analytics.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/pages/card-analytics.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/plugins/tour/tour.css') }}">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url('admin/app-assets/css-rtl/custom-rtl.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url('admin/assets/css/style-rtl.css') }}">
    <!-- END: Custom CSS-->

    <!-- END: style CSS arabic -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu-modern 2-columns  navbar-floating footer-static  " data-open="click" data-menu="vertical-menu-modern" data-col="2-columns" style="font-family: 'Cairo', sans-serif;
">

<!-- BEGIN: navbar -->

<!-- END: navbar -->


<!-- BEGIN: sidebar -->
@include('Admin.layout.sidebar')
<!-- END: sidebar -->




    <!-- BEGIN: Content-->

        <!-- real rashed pakedge -->
        @include('sweetalert::alert')

        @yield('content')

    <!-- END: Content-->



<!-- BEGIN: footer -->

<!-- END: footer -->



    <!-- BEGIN: Vendor JS-->
    <script src="{{ url('admin/app-assets/vendors/js/vendors.min.js') }}"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <script src="{{ url('admin/app-assets/vendors/js/charts/apexcharts.min.js') }}"></script>
    <script src="{{ url('admin/app-assets/vendors/js/extensions/tether.min.js') }}"></script>
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="{{ url('admin/app-assets/js/core/app-menu.js') }}"></script>
    <script src="{{ url('admin/app-assets/js/core/app.js') }}"></script>
    <script src="{{ url('admin/app-assets/js/scripts/components.js') }}"></script>
    <!-- END: Theme JS-->


    @yield('scripts')

    <script src="{{ url('admin/assets/js/jquery.min.js') }}"></script>

    <!-- BEGIN: Page JS-->
    <script src="{{ url('admin/app-assets/js/scripts/pages/dashboard-analytics.js') }}"></script>
    <!-- END: Page JS-->
    <script src="{{ url('admin/app-assets/js/scripts/summernote-ext-rtl.js') }}"></script>



    @yield('dataTable')


</body>
<!-- END: Body-->

</html>

resources/views/Admin/layout/footer.blade.php
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>


        <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light">
        <p class="clearfix blue-grey lighten-2 mb-0"><span class="float-md-left d-block d-md-inline-block mt-25"><a class="text-bold-800 grey darken-2" href="https://1.envato.market/pixinvent_portfolio" target="_blank"></a>جميع الحقوق محفوظه لدي موقع <b style="color: #7468f0">اذونات</b></span><span class="float-md-right d-none d-md-block">تصميم وتطوير شركة جداره للتقنيه <img src="{{ url('admin/jaadara.png') }}" width="50px"></span>
            <button class="btn btn-primary btn-icon scroll-top" type="button"><i class="feather icon-arrow-up"></i></button>
        </p>
    </footer>
    <!-- END: Footer-->

resources/views/Admin/layout/messageErrorLogin.blade.php
	    @if(session()->has('error'))
	        <div class="alert alert-danger" style="width: 685px;">
	            {{ session()->get('error') }}
	        </div>
	    @endif

resources/views/Admin/layout/messages.blade.php
		@if ($errors->any())
		    <div class="alert alert-danger">
		        <ul>
		            @foreach ($errors->all() as $error)
		                <li>{{ $error }}</li>
		            @endforeach
		        </ul>
		    </div>
		@endif
	 

resources/views/Admin/layout/sidebar.blade.php
    <!-- BEGIN: Header-->
    <nav class="header-navbar navbar-expand-lg navbar navbar-with-menu floating-nav navbar-light navbar-shadow">
        <div class="navbar-wrapper">
            <div class="navbar-container content">
                <div class="navbar-collapse" id="navbar-mobile">
                    <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                        <ul class="nav navbar-nav">
                            <li class="nav-item mobile-menu d-xl-none mr-auto"><a
                            class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i
                            class="ficon feather icon-menu"></i></a></li>
                        </ul>
                    </div>
                    <ul class="nav navbar-nav float-right">
                        <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                                <div class="user-nav d-sm-flex d-none"><span class="user-name text-bold-600">{{ Auth::user()->name }}</span></div><span><img class="round" src="{{ url('Admin/app-assets/images/portrait/small/avatar-s-11.jpg') }}" alt="avatar" height="40" width="40"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">

                                <form action="{{ route('logout') }}" method="get">
                                    <button class="dropdown-item"><i class="feather icon-power"></i> تسجيل خروج</button>
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

<!-- BEGIN: Main Menu-->
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="navbar-header">
        <ul class="nav navbar-nav flex-row">
        <li class="nav-item mr-auto"><a class="navbar-brand" href="{{url('/')}}">
                <img src="{{ url('Website/images/main/logo.png') }}" height="100px">
                </a></li>
            <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="feather icon-x d-block d-xl-none font-medium-4 primary toggle-icon"></i><i class="toggle-icon feather icon-disc font-medium-4 d-none d-xl-block collapse-toggle-icon primary" data-ticon="icon-disc"></i></a></li>
        </ul>
    </div>
    <div class="shadow-bottom"></div>
    <div class="main-menu-content">

        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

        <li class="{{Request::segment(2) == 'welcome'?'active':''}} nav-item"><a href="{{route('welcome')}}"><i class="feather icon-home"></i><span class="menu-title" data-i18n="Email">الرئيسيه</span></a></li>

        <li class="{{Request::segment(2) == 'categories'?'active':''}} nav-item"><a href="{{route('categories.index')}}"><i class="feather icon-folder"></i><span class="menu-title" data-i18n="Email">الاقسام</span></a></li>

        <li class="{{Request::segment(2) == 'subcategories'?'active':''}} nav-item"><a href="{{route('subcategories.index')}}"><i class="feather icon-copy"></i><span class="menu-title" data-i18n="Email">الاقسام الفرعيه</span></a></li>

        <li class="{{Request::segment(2) == 'subsubcategories'?'active':''}} nav-item"><a href="{{route('subsubcategories.index')}}"><i class="feather icon-corner-right-down"></i><span class="menu-title" data-i18n="Email">الاقسام الثانوية </span></a></li>

        <li class="{{Request::segment(2) == 'contents'?'active':''}} nav-item"><a href="{{route('contents.index')}}"><i class="feather icon-file"></i><span class="menu-title" data-i18n="Email">المحتوي</span></a></li>


        <li class="{{Request::segment(2) == 'settings'?'active':''}} nav-item"><a href="{{route('settings.create')}}"><i class="feather icon-settings"></i><span class="menu-title" data-i18n="Email">الاعدادات</span></a></li>                                

        </ul>

    </div>
</div>
<!-- END: Main Menu-->